language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

install:
   - python setup.py install

#   # command to run tests
#   script:
#     - pytest
